SELECT iu.QUADRA, COUNT(iu.INSCRICAO) AS TOTAL_IMOVEIS, SUM(i.PRECO_VENDA) AS SOMA_VALOR_VENDA
FROM IMOVEL_URBANO iu
JOIN IMOVEL i ON iu.INSCRICAO = i.INSCRICAO
GROUP BY iu.QUADRA
ORDER BY SOMA_VALOR_VENDA DESC;
