SELECT 
    i.INSCRICAO,
    i.PRECO_VENDA,
    i.AREA_TOTAL,
    i.CPF_PROPRIETARIO
FROM 
    IMOVEL i
WHERE 
    i.PRECO_VENDA > (
        SELECT AVG(PRECO_VENDA)
        FROM IMOVEL
    )
ORDER BY 
    i.PRECO_VENDA DESC;
