Field	Type	Null	Key	Default	Extra
NUMERO_SEGMENTO	int(11)	NO	PRI	NULL	
NUMERO_VOO	int(11)	NO	PRI	NULL	
CODIGO_AEROPORTO_PARTIDA	int(11)	YES	MUL	NULL	
CODIGO_AEROPORTO_CHEGADA	int(11)	YES	MUL	NULL	
HORARIO_PREVISTO_PARTIDA	time	NO		NULL	
HORARIO_PREVISTO_CHEGADA	time	NO		NULL	
PREFIXO	varchar(20)	YES	MUL	NULL	
