Field	Type	Null	Key	Default	Extra
NUMERO_VOO	int(11)	NO	PRI	NULL	
NUMERO_SEGMENTO	int(11)	NO	PRI	NULL	
DATA_INSTANCIA	date	NO	PRI	NULL	
HORARIO_PARTIDA_AEROPORTO	time	NO	PRI	NULL	
HORARIO_CHEGADA_AEROPORTO	time	NO		NULL	
NUMERO_ASSENTOS_DISPONIVEIS	int(11)	YES		NULL	
