Field	Type	Null	Key	Default	Extra
INSCRICAO	int(11)	NO	PRI	NULL	
PRECO_VENDA	float	NO		NULL	
AREA_TOTAL	float	NO		NULL	
COD_ENDERECO	int(11)	NO	MUL	NULL	
CPF_PROPRIETARIO	varchar(11)	NO	MUL	NULL	
DTA_EXPIRACAO	date	NO		NULL	
