Table	Non_unique	Key_name	Seq_in_index	Column_name	Collation	Cardinality	Sub_part	Packed	Null	Index_type	Comment	Index_comment
INSTANCIA_DE_SEGMENTO	0	PRIMARY	1	NUMERO_VOO	A	5	NULL	NULL		BTREE		
INSTANCIA_DE_SEGMENTO	0	PRIMARY	2	NUMERO_SEGMENTO	A	5	NULL	NULL		BTREE		
INSTANCIA_DE_SEGMENTO	0	PRIMARY	3	DATA_INSTANCIA	A	5	NULL	NULL		BTREE		
INSTANCIA_DE_SEGMENTO	0	PRIMARY	4	HORARIO_PARTIDA_AEROPORTO	A	5	NULL	NULL		BTREE		
