/* Tabela 1: AEROPORTO */
CREATE TABLE AEROPORTO(
   CODIGO_AEROPORTO INT AUTO_INCREMENT PRIMARY KEY,
   NOME_AEROPORTO VARCHAR(50),
   CIDADE VARCHAR(50),
   ESTADO VARCHAR(2)
);

/* Tabela 2: TIPO_AVIAO */
CREATE TABLE TIPO_AVIAO(
    NOME_TIPO VARCHAR(20) PRIMARY KEY,
    NUMERO_MAXIMO_ASSENTOS INT,
    EMPRESA_FABRICANTE VARCHAR(50)
);

/* Tabela 3: POUSA (Tabela associativa entre Aeroporto e Tipo_Avião) */
CREATE TABLE POUSA(
    CODIGO_AEROPORTO INT,
    NOME_TIPO VARCHAR(20),
    FOREIGN KEY(CODIGO_AEROPORTO) REFERENCES AEROPORTO(CODIGO_AEROPORTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY(NOME_TIPO) REFERENCES TIPO_AVIAO(NOME_TIPO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    PRIMARY KEY (CODIGO_AEROPORTO, NOME_TIPO)
);

/* Tabela 4: AVIAO */
CREATE TABLE AVIAO(
    PREFIXO VARCHAR(20) PRIMARY KEY,
    NUMERO_TOTAL_ASSENTOS INT,
    NOME_TIPO VARCHAR(20),
    FOREIGN KEY(NOME_TIPO) REFERENCES TIPO_AVIAO(NOME_TIPO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

/* Tabela 5: VOO */
CREATE TABLE VOO(
    NUMERO_VOO INT AUTO_INCREMENT PRIMARY KEY,
    EMPRESA VARCHAR(50)
);

/* Tabela 6: DIAS_SEMANAS_VOO (Atributo multivalorado de VOO) */
/* (0=Domingo, 1=Segunda, ..., 6=Sábado) */
CREATE TABLE DIAS_SEMANAS_VOO(
    DIA_SEMANA INT,
    NUMERO_VOO INT,
    FOREIGN KEY(NUMERO_VOO) REFERENCES VOO(NUMERO_VOO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    PRIMARY KEY (DIA_SEMANA, NUMERO_VOO)
);

/* Tabela 7: SEGMENTO_VOO */
CREATE TABLE SEGMENTO_VOO(
    NUMERO_SEGMENTO INT,
    NUMERO_VOO INT,
    CODIGO_AEROPORTO_PARTIDA INT,
    CODIGO_AEROPORTO_CHEGADA INT,
    HORARIO_PREVISTO_PARTIDA TIME NOT NULL,
    HORARIO_PREVISTO_CHEGADA TIME NOT NULL,
    PREFIXO VARCHAR(20),
    PRIMARY KEY(NUMERO_VOO, NUMERO_SEGMENTO),
    FOREIGN KEY(NUMERO_VOO) REFERENCES VOO(NUMERO_VOO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY(CODIGO_AEROPORTO_PARTIDA) REFERENCES AEROPORTO(CODIGO_AEROPORTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY(CODIGO_AEROPORTO_CHEGADA) REFERENCES AEROPORTO(CODIGO_AEROPORTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY(PREFIXO) REFERENCES AVIAO(PREFIXO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

/* Tabela 8: INSTANCIA_DE_SEGMENTO */
CREATE TABLE INSTANCIA_DE_SEGMENTO(
    NUMERO_VOO INT,
    NUMERO_SEGMENTO INT,
    DATA_INSTANCIA DATE NOT NULL,
    HORARIO_PARTIDA_AEROPORTO TIME NOT NULL,
    HORARIO_CHEGADA_AEROPORTO TIME NOT NULL,
    NUMERO_ASSENTOS_DISPONIVEIS INT,
    FOREIGN KEY(NUMERO_VOO, NUMERO_SEGMENTO) REFERENCES SEGMENTO_VOO(NUMERO_VOO, NUMERO_SEGMENTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    PRIMARY KEY(NUMERO_VOO, NUMERO_SEGMENTO, DATA_INSTANCIA, HORARIO_PARTIDA_AEROPORTO)
);