CREATE TABLE PESSOA(
   NOME VARCHAR(20),
   CPF  VARCHAR(11) PRIMARY KEY
);

CREATE TABLE COMPRADOR (
   LISTA_PREFS_TIPOS_IMOVEIS VARCHAR(255),
   PROFISSAO VARCHAR(255),
   CPF VARCHAR(11) PRIMARY KEY,
   FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
       ON DELETE CASCADE
       ON UPDATE CASCADE
);

CREATE TABLE CORRETOR (
   NUM_CRECI INT,
   DTA_ADMISSAO DATE,
   CPF VARCHAR(11) PRIMARY KEY,
   FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
       ON DELETE CASCADE
       ON UPDATE CASCADE
);

CREATE TABLE PROPRIETARIO (
   ESTADO_CIVIL VARCHAR(20),
   CPF VARCHAR(11) PRIMARY KEY,
   FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
       ON DELETE CASCADE
       ON UPDATE CASCADE
);

CREATE TABLE PROMESSACOMPRA (
    ID_PROMESSA INT AUTO_INCREMENT PRIMARY KEY,
    DATA_EXPIRACAO DATE NOT NULL,
    INSCRICAO INT NOT NULL,
    PRIORIDADE INT NOT NULL,
    CPF_COMPRADOR VARCHAR(11) NOT NULL,
    CPF_CORRETOR VARCHAR(11) NOT NULL,
    FOREIGN KEY (CPF_COMPRADOR) REFERENCES COMPRADOR(CPF)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (CPF_CORRETOR) REFERENCES CORRETOR(CPF)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY(INSCRICAO) REFERENCES IMOVEL(INSCRICAO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ENDERECO (
    COD_ENDERECO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_RUA VARCHAR(100) NOT NULL,
    NUMERO_CASA INT NOT NULL,
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR(50) NOT NULL,
    TIPO_ENDERECO VARCHAR(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE TELEFONE (
    NUMERO_ORDEM INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO VARCHAR(15) NOT NULL,
    PREFIXO VARCHAR(10) NOT NULL,
    COD_ENDERECO INT NOT NULL,
    FOREIGN KEY (COD_ENDERECO) REFERENCES ENDERECO(COD_ENDERECO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IMOVEL (
    INSCRICAO INT PRIMARY KEY,
    PRECO_VENDA FLOAT NOT NULL,
    AREA_TOTAL FLOAT NOT NULL,
    COD_ENDERECO INT NOT NULL,
    CPF_PROPRIETARIO VARCHAR(11) NOT NULL,
    DTA_EXPIRACAO DATE NOT NULL, 
    FOREIGN KEY (CPF_PROPRIETARIO) REFERENCES PESSOA(CPF)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (COD_ENDERECO) REFERENCES ENDERECO(COD_ENDERECO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE EDIFICACAO (
    ID_EDIFICACAO INT AUTO_INCREMENT PRIMARY KEY,
    AREA_CONSTRUIDA FLOAT NOT NULL,
    PADRAO_CONSTRUCAO VARCHAR(50) NOT NULL,
    DESTINACAO VARCHAR(50) NOT NULL,
    HABITADA BOOLEAN NOT NULL,
    INSCRICAO_IMOVEL INT NOT NULL,
    FOREIGN KEY (INSCRICAO_IMOVEL) REFERENCES IMOVEL(INSCRICAO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IMOVEL_URBANO (
    INSCRICAO INT PRIMARY KEY,
    COD_LOTEAMENTO INT NOT NULL,
    QUADRA VARCHAR(10) NOT NULL,
    NUM_ORDEM_QUADRA INT NOT NULL,
    FOREIGN KEY (INSCRICAO) REFERENCES IMOVEL(INSCRICAO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IMOVEL_RURAL (
    INSCRICAO INT PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    TAXA_ITR FLOAT NOT NULL,
    LISTA_MELHORIAS VARCHAR(255),
    FOREIGN KEY (INSCRICAO) REFERENCES IMOVEL(INSCRICAO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX idx_nome ON PESSOA(NOME);

CREATE INDEX idx_lista_prefs_tipos_imoveis on COMPRADOR(LISTA_PREFS_TIPOS_IMOVEIS);
CREATE INDEX idx_profissao on COMPRADOR(PROFISSAO);

CREATE INDEX idx_num_creci on CORRETOR(NUM_CRECI);
CREATE INDEX idx_dta_admissao on CORRETOR(DTA_ADMISSAO);

CREATE INDEX idx_estado_civil on PROPRIETARIO(ESTADO_CIVIL);

CREATE INDEX idx_dta_expiracao on PROMESSACOMPRA(DTA_EXPIRACAO);
CREATE INDEX idx_prioridade on PROMESSACOMPRA(PRIORIDADE);

CREATE INDEX idx_nome_rua on ENDERECO(NOME_RUA);
CREATE INDEX idx_numero_casa on ENDERECO(NUMERO_CASA);
CREATE INDEX idx_complemento on ENDERECO(COMPLEMENTO);
CREATE INDEX idx_bairro on ENDERECO(BAIRRO);
CREATE INDEX idx_tipo_endereco on ENDERECO(TIPO_ENDERECO);

CREATE INDEX idx_numero on  TELEFONE(NUMERO);
CREATE INDEX idx_prefixo on TELEFONE(PREFIXO);
    
CREATE INDEX idx_preco_venda on IMOVEL(PRECO_VENDA);
CREATE INDEX idx_area_total on IMOVEL(AREA_TOTAL);
CREATE INDEX idx_dta_expiracao on IMOVEL(DTA_EXPIRACAO);
    
CREATE INDEX idx_area_construida on EDIFICACAO(AREA_CONSTRUIDA);
CREATE INDEX idx_padrao_construcao on EDIFICACAO(PADRAO_CONSTRUCAO);
CREATE INDEX idx_destinacao on EDIFICACAO(DESTINACAO);
CREATE INDEX idx_habitada on EDIFICACAO(HABITADA);
    
CREATE INDEX idx_quadra on IMOVEL_URBANO(QUADRA);
CREATE INDEX idx_num_ordem_quadra on IMOVEL_URBANO(NUM_ORDEM_QUADRA);
    
CREATE INDEX idx_tipo on IMOVEL_RURAL(TIPO);
CREATE INDEX idx_taxa_itr on IMOVEL_RURAL(TAXA_ITR);
CREATE INDEX idx_lista_melhorias on IMOVEL_RURAL(LISTA_MELHORIAS);
